eureka:
  client:
    service-url:
      register-with-eureka: false
      fetch-registry: false
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8761
spring:
  application:
    name: eureka-server